---
apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-system-service-discovery

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5.conf
  namespace: tanzu-system-service-discovery
data:
  krb5.conf: |
    [logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

    [libdefaults]
    dns_lookup_realm = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    pkinit_anchors = /etc/pki/tls/certs/ca-bundle.crt
    default_ccache_name = KEYRING:persistent:%{uid}

    default_realm = CMBU.LOCAL

    [realms]
    CMBU.LOCAL = {
      kdc = cmbu-wdcdc-02.cmbu.local
      admin_server = cmbu-wdcdc-02.cmbu.local
    }

    [domain_realm]
    cmbu.local = CMBU.LOCAL
    .cmbu.local = CMBU.LOCAL
